* Adrian Notes
  Good work here. I have a couple of minor notes:
1. [X] On the second heading of slide 4, you have a double space typo.
2. [ ] On slides 17 and 25, you're using EXT as the prefix for a
   multi-ventor extension seems odd. Let's consider MULTI as the
   prefix for that. This might be a bit less confusing.
3. [ ] On slide 17, you list Rackspace explicitly in the upper table. I
   have a feeling that the OpenStack community would prefer not to see
   any special cases for Rackspace. I suggest clearly labeling that
   table as an example, and put at least one other community member in
   there, and some ... indicating that more are expected. You make
   reference to a registry for that, so I think your intent was to
   show that anyone could get their own prefix. Let's make an effort
   to clarify this. It might be best to pull Rackspace out of the
   example table. Consider:

   OS = OpenStack
   MULTI = Multi-Vendor extension
   ARB-PREFIX = where PREFIX is an ARB registered+approved vendor ID
   NNN = where NNN is a registered prefix for a vendor (ie: Rackspace)
4. [ ] On slides 19-21 what does "... use(s) alias" mean, with respect to JSON?
5. [ ] On slide 31 you wrote "Language bindings may be written to
   detect and give access to extensions given a WADL, though that
   would be challenging.". Why? This definitely sounds like the right
   approach. I don't fully understand why this is challenging.

